const UPD_DATA = 'UPD_DATA';
const POST_DATA = 'POST_DATA';
const DEL_DATA = 'DEL_DATA';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';

export { UPD_DATA, CLOSE_MODAL, POST_DATA, DEL_DATA, OPEN_MODAL }