const ADD_DATA = 'ADD_DATA';
const UPD_DATA = 'UPD_DATA';
const ABOUT_INGR = 'ABOUT_INGR';
const CLOSE_MODAL = 'CLOSE_MODAL';
const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';

export { ADD_DATA, UPD_DATA, ABOUT_INGR, CLOSE_MODAL, GET_ORDER_NUMBER }